### ISSUE TITLE
"Edit on Github" and other links to Github repo

### ISSUE THREAD

**Issue by janpio** [prisma/dataguide#14]
Right now there are no links to this GH repo from the actual site.

**Comment by imchairmanm** [comment]
This can follow the design used in the docs.  For example, on the bottom of [this page](https://www.prisma.io/docs/understand-prisma/data-modeling), you see:

![Screenshot from 2020-09-07 15-53-35](https://user-images.githubusercontent.com/3957147/92394781-6f7f0980-f122-11ea-86cb-883d0dcbb06c.png)
