### ISSUE TITLE
Search functionality for dataguide

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#141]
As per discussion here: https://prisma-company.slack.com/archives/CJ5U1BS2X/p1618386028009300

Basically just porting the search functionality from the docs to the data guide.

**Comment by carlagn** [comment]
Done here: https://github.com/prisma/dataguide/pull/361 waiting for designs!

**Comment by carlagn** [comment]
**Update:**

- Functionality has been approved (reviewed by @meletj and @imchairmanm 
- Designs are semi-approved:
  - A re-design for the initial placement of the search bar on the index page needs to be done.
  - Design for specific pages has been approved (it does not require a change of placement for the input search bar, as it is already on the header).
