### ISSUE TITLE
SEO updates for intro to serverless article

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#193]
Hey there @mrbeatus and @mkrasne2,

This was an article we published last week that we figured could use an SEO audit to get it up to snuff.  Would you mind creating a PR with the changes we should make?

Here's the article:

* Published version: https://www.prisma.io/dataguide/serverless/what-is-serverless
* Source file: https://github.com/prisma/dataguide/blob/main/content/11-serverless/01-what-is-serverless.mdx

Let me know if you have any questions.  Thanks!

**Comment by mkrasne2** [comment]
<img width="1127" alt="Screen Shot 2021-11-08 at 6 25 54 PM" src="https://user-images.githubusercontent.com/70119343/140834262-80b0ad0f-12c1-4022-8867-544c9024a60b.png">

Hello Justin!

Glad to provide some feedback on the metadata - here's a screenshot of what I'd recommend. Wanted to get your thoughts before creating a pull request.

Thanks!

**Comment by imchairmanm** [comment]
Hey there, sorry about the delay in responding.  I created a [pull request with your changes](https://github.com/prisma/dataguide/pull/196).  Could you give it a look when you have a moment and verify that it implements your suggestions here?

**Comment by mkrasne2** [comment]
Your pull request looks great to me! It matches the optimizations we recommended. Thank you, @imchairmanm
