### ISSUE TITLE
SEO updates for serverless comparison article

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#199]
Hey there @mrbeatus and @mkrasne2,

Here's another serverless article that we recently published.  Would love to get your thoughts on SEO improvements. Would you mind creating a PR with the changes we should make?

Here's the article:

Published version: https://www.prisma.io/dataguide/serverless/serverless-comparison
Source file: https://github.com/prisma/dataguide/blob/main/content/11-serverless/02-serverless-comparison.mdx
Let me know if you have any questions. Thanks!

**Comment by mkrasne2** [comment]
Glad to help! Just created a PR for metadata updates for this new page.

**Comment by imchairmanm** [comment]
Awesome. Thanks for the help.  I just merged that in, so I'll close this :+1:
