### ISSUE TITLE
The homepage shows a loader when you switch to a different tab, and back

### ISSUE THREAD

**Issue by madebysid** [prisma/dataguide#22]
Pretty small thing, just noticed it after today's announcement. To reproduce,
1. Open https://dataguide.prisma.io/ in Firefox (it only seems to happen in Firefox, and only on the home page
2. Open a new tab. 
3. Switch to the new tab
4. Switch back to the dataguide tab

![Screen-Recording-2020-06-26-at-1(1)](https://user-images.githubusercontent.com/7689783/85867373-16613400-b7c9-11ea-8ef8-4b6ae1a96368.gif)

(Sorry, I don't have a proper GIF maker :D)

**Comment by janpio** [comment]
Can not reproduce on Windows (but that does not mean much, codebase of FF is quite different)

**Comment by imchairmanm** [comment]
I was unable to reproduce also.  On Firefox 80.0.1 (64-bit) on Linux (Ubuntu 20.04)

**Comment by madebysid** [comment]
I can no longer seet his either, closing 🤷‍♂️
