### ISSUE TITLE
Add link to prisma homepage in the footer

### ISSUE THREAD

**Issue by pantharshit00** [prisma/dataguide#23]
Right now we don't link our homepage anywhere in the dataguide

**Comment by etelsv** [comment]
Just wanted to follow up on this. We have no links back to Prisma on the site. Here are 2 places where a link would be good. 
<img width="302" alt="Screen Shot 2020-07-23 at 3 09 54 PM" src="https://user-images.githubusercontent.com/42931286/88291079-02412180-ccf8-11ea-8087-5a301ec8b662.png">
<img width="972" alt="Screen Shot 2020-07-23 at 3 09 49 PM" src="https://user-images.githubusercontent.com/42931286/88291167-1b49d280-ccf8-11ea-8a55-e49c5ce60c32.png">
