### ISSUE TITLE
Improve performances

### ISSUE THREAD

**Issue by smakosh** [prisma/dataguide#26]
## Description
After running an Audit lighthouse test, I noticed that there is room for improvement specially for performances, here are some screenshots that can help

![Screen Shot 2020-07-09 at 13 26 40](https://user-images.githubusercontent.com/20082141/87040657-f2e6b200-c1e8-11ea-904d-d09a12cfcffc.png)
![Screen Shot 2020-07-09 at 13 26 48](https://user-images.githubusercontent.com/20082141/87040660-f4b07580-c1e8-11ea-9c63-c17cd399ca88.png)
![Screen Shot 2020-07-09 at 13 26 57](https://user-images.githubusercontent.com/20082141/87040665-f67a3900-c1e8-11ea-9e0f-32a77b38777e.png)
![Screen Shot 2020-07-09 at 13 27 04](https://user-images.githubusercontent.com/20082141/87040669-f712cf80-c1e8-11ea-95b4-cec2d1995df4.png)

**Comment by hrescak** [comment]
We'll do a general performance pass at a later date. Thank you so much for bringing this to our attention!
