### ISSUE TITLE
Add collapsible sections on the left hand side

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#263]
With the data guide growing, it would be helpful to be able to have a more compact left-hand navigation experience.  It might make sense for us to have the Data Guide sections be collapsible.

So I guess my suggestion would be to have all of the sections collapsed by default except for the current section and allow users to click to open additional sections.

**Comment by nilubava** [comment]
Hi @imchairmanm Is this still relevant? If not, could you close this issue?
If yes, add me as assignee :)

**Comment by nilubava** [comment]
@nikolasburk

**Comment by nikolasburk** [comment]
Since we're not planning to invest further into the Data Guide, I think we can close this one 👍
