### ISSUE TITLE
Code snippets interpret leading `-` as "remove" and render lines in red

### ISSUE THREAD

**Issue by nikolasburk** [prisma/dataguide#278]
Several examples on this page: https://www.prisma.io/dataguide/postgresql/authentication-and-authorization/role-management

For example:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/4058327/160801497-40ca26f2-bf5b-4a76-a4ad-de2e8716e276.png">

**Comment by imchairmanm** [comment]
Thanks for the heads up.  We noted this back here, but looks like we haven't been able to prioritize it yet 

https://github.com/prisma/dataguide/issues/11

**Comment by imchairmanm** [comment]
It does the same with `+` too in a few cases where those are used as section dividers.

**Comment by janpio** [comment]
I think we had the same in the main docs - there might be an issue indicating if this was closed/resolved or is still present. (We might have changed to having to activate it on the code block somehow)
