### ISSUE TITLE
Automatic slack notifications when a new Data Guide article is published

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#312]
Because there are some routine downstream actions that typically need to take place once an article is published on the Data Guide, it'd be helpful to be able to automatically post in a slack channel on any new content.

Zapier was mentioned as a possible implementation.

**Comment by janpio** [comment]
https://github.com/prisma/dataguide/issues/313 would make that trivial.

**Comment by nilubava** [comment]
Hi @imchairmanm Is this still relevant? If not, could you close this issue?
If yes, add me as assignee :)

**Comment by nilubava** [comment]
@nikolasburk

**Comment by nikolasburk** [comment]
I don't think we currently have a channel where posting this would feel appropriate, I think we can close this for now 👍
