### ISSUE TITLE
New tool tip component

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#48]
Once we have a glossary for the data guide (#47) , a tool tip component that auto-populates definitions from the glossary would be extremely useful.  You can find an explanation for [the full proposal here](https://www.notion.so/prismaio/Proposal-for-new-glossary-and-tool-tips-integrations-to-the-data-guide-7c07b6dce8e047dda0ff8135221a4340).

In short, it'd be great to be able to wrap a word or words within an article with a component to automatically pull information from a specific term within the glossary.  The tool tip component could potentially work something like this:

```
<tooltip id="id-set-in-the-glossary">term to get a tool tip</tooltip>
```

The idea being that you could manually wrap text with the component and specify a unique ID from the glossary to automatically fill in the tool tip content.

The tool tip content would ideally include the following information:

* A link to the specific entry within the glossary.  For example, a link in the tool tip header that says "From the data guide glossary for 'columns':"
* The terminology and definition pulled from the glossary.
* The "Learn more" link given within the glossary entry to point readers to an article that can give them additional context.

**Comment by imchairmanm** [comment]
The design for this can be found in the figma file linked from here (sorry, I'm not sure how to link to specific images in the vast figma board view): https://www.notion.so/prismaio/Glossary-page-New-Glossary-tooltip-and-Vocab-review-components-for-the-Data-Guide-5270160d69bc4864acb69970b9968c74

**Comment by nilubava** [comment]
Hi @imchairmanm Is this still relevant? If not, could you close this issue?
If yes, add me as assignee :)

**Comment by nilubava** [comment]
@nikolasburk

**Comment by nikolasburk** [comment]
Since we're not planning to invest further into the Data Guide, I think we can close this one 👍
