### ISSUE TITLE
New vocab review component

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#49]
Once we have a glossary for the data guide (#47) and a tool tip component to auto-populate glossary definitions (#48), a vocabulary review component that automatically creates a vocab review section at the bottom of articles with definitions from the glossary would be great.  You can find an explanation for [the full proposal here](https://www.notion.so/prismaio/Proposal-for-new-glossary-and-tool-tips-integrations-to-the-data-guide-7c07b6dce8e047dda0ff8135221a4340).

Basically, if we have a glossary and tool tips, it'd be really helpful to have a component that auto-populates a "vocab review" or "terminology review" section at the end of articles.  The information would be populated based on:

* The tool tips used within the article
* The terms and definitions provided by the glossary
* New terminology identified by glossary entries that use this article as their "Learn more" link

My initial idea behind the review section is to have it divided into two sections, each of which will only be displayed if the relevant content exists:

* A "referenced terminology" section that reprises all of the tool tips included within the article.  The terms and definitions are provided once again in a group in this section to make it easy to review related or prerequisite knowledge.
* A "new terminology" section that is populated based on entries within the glossary that use _this_ article as their "Learn more" link.  The article will likely not use tool tips for terminology that it is introducing and instead will define the term inline.  However, using the "Learn more" links from the glossary is a good way to identify new terminology introduced and thoroughly defined by this article.  This section will contain all of the new terms that are in this article as identified by the links back to this article.

**Comment by imchairmanm** [comment]
The design for this can be found in the figma file linked from here (sorry, I'm not sure how to link to specific images in the vast figma board view): https://www.notion.so/prismaio/Glossary-page-New-Glossary-tooltip-and-Vocab-review-components-for-the-Data-Guide-5270160d69bc4864acb69970b9968c74

**Comment by nilubava** [comment]
Hi @imchairmanm Is this still relevant? If not, could you close this issue?
If yes, add me as assignee :)

**Comment by nilubava** [comment]
@nikolasburk

**Comment by nikolasburk** [comment]
Since we're not planning to invest further into the Data Guide, I think we can close this one 👍
