### ISSUE TITLE
Ability to easily add a small border or shadow around images

### ISSUE THREAD

**Issue by imchairmanm** [prisma/dataguide#8]
Some of images we in the articles have backgrounds that kind of blend into the background of the article.  This isn't a big deal in most cases, but when they're text heavy images, it can start to interfere with the way the page reads since it's difficult to tell what is part of the image and what is part of the page's text.  There's a good example of that [here](https://dataguide.prisma.io/postgresql/setting-up-a-local-postgresql-database#setting-up-postgresql-on-windows).

It would be great to be able to use styling to easily make these stand out a bit more without having to edit the images themselves.  I could see it being an optional component that can be applied ad-hoc to images that suffer from this problem, or a more uniform solution that changes the styling to avoid the blending in the first place.  I have no idea which is preferable, but I thought it might be worthwhile to prevent confusion among readers.

**Comment by nilubava** [comment]
Hi @imchairmanm Is this still relevant? If not, could you close this issue?
If yes, add me as assignee :)

**Comment by nilubava** [comment]
@nikolasburk
